name: Frontend CI/CD

on:
  pull_request:
    branches: [ deployment ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build frontend Docker image
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          docker build -t front-image:$COMMIT_HASH .
          docker tag front-image:$COMMIT_HASH front-image:latest

      - name: Install kubectl if not installed
        run: |
          if ! command -v kubectl &> /dev/null; then
            echo "Installing kubectl..."
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin/
          fi

      - name: Deploy frontend to Minikube
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          kubectl set image deployment/frontend-deployment \
            frontend=front-image:$COMMIT_HASH
